// half_orm_gen/frontend/angular/v19/new-items-badge.component.ts
import { Component, input, output } from '@angular/core';

@Component({
  selector: 'app-new-items-badge',
  standalone: true,
  template: `
    @if (count() > 0) {
      <button type="button" (click)="toggle.emit()"
              class="text-xs font-medium px-2 py-1 rounded-full border transition-colors"
              [class.bg-blue-600]="active()" [class.text-white]="active()" [class.border-blue-600]="active()"
              [class.bg-blue-50]="!active()" [class.text-blue-700]="!active()" [class.border-blue-200]="!active()">
        +{{ count() }} new
      </button>
    }
  `,
})
export class NewItemsBadgeComponent {
  readonly count  = input(0);
  readonly active = input(false);
  readonly toggle = output<void>();
}

// half_orm_gen/frontend/svelte/v5/NewItemsBadge.svelte
<script lang="ts">
  let {
    count,
    active = false,
    ontoggle,
  }: {
    count: number;
    active?: boolean;
    ontoggle: () => void;
  } = $props();
</script>

{#if count > 0}
  <button type="button" onclick={ontoggle}
          class="text-xs font-medium px-2 py-1 rounded-full border transition-colors {active ? 'bg-blue-600 text-white border-blue-600' : 'bg-blue-50 text-blue-700 border-blue-200'}">
    +{count} new
  </button>
{/if}
