// half_orm_gen/frontend/svelte/v5/FilterHelpTooltip.svelte
<div class="group absolute right-1.5 top-1/2 -translate-y-1/2">
  <span class="flex h-3.5 w-3.5 items-center justify-center rounded-full bg-gray-200 text-[9px] font-semibold text-gray-500 cursor-help select-none">?</span>
  <div class="pointer-events-none invisible absolute right-0 top-full z-20 mt-2 w-64 rounded-lg border border-gray-200 bg-white p-3 text-[11px] leading-relaxed text-gray-700 shadow-lg opacity-0 transition-opacity duration-150 group-hover:visible group-hover:opacity-100">
    <div class="absolute -top-1 right-2 h-2 w-2 rotate-45 border-l border-t border-gray-200 bg-white"></div>
    <ul class="space-y-1">
      <li class="flex gap-1.5"><code class="shrink-0 rounded bg-gray-100 px-1 py-0.5 text-[10px] text-gray-800">text</code><span>starts with</span></li>
      <li class="flex gap-1.5"><code class="shrink-0 rounded bg-gray-100 px-1 py-0.5 text-[10px] text-gray-800">*text</code><span>anywhere in the field</span></li>
      <li class="flex gap-1.5"><code class="shrink-0 rounded bg-gray-100 px-1 py-0.5 text-[10px] text-gray-800">&gt; &lt; &gt;= &lt;=</code><span>numeric/date comparison</span></li>
      <li class="flex gap-1.5"><code class="shrink-0 rounded bg-gray-100 px-1 py-0.5 text-[10px] text-gray-800">&gt;=A&lt;=B</code><span>range</span></li>
    </ul>
  </div>
</div>

// half_orm_gen/frontend/angular/v19/filter-help-tooltip.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-filter-help-tooltip',
  standalone: true,
  host: { class: 'group absolute right-1.5 top-1/2 -translate-y-1/2' },
  template: `
    <span class="flex h-3.5 w-3.5 items-center justify-center rounded-full bg-gray-200 text-[9px] font-semibold text-gray-500 cursor-help select-none">?</span>
    <div class="pointer-events-none invisible absolute right-0 top-full z-20 mt-2 w-64 rounded-lg border border-gray-200 bg-white p-3 text-[11px] leading-relaxed text-gray-700 shadow-lg opacity-0 transition-opacity duration-150 group-hover:visible group-hover:opacity-100">
      <div class="absolute -top-1 right-2 h-2 w-2 rotate-45 border-l border-t border-gray-200 bg-white"></div>
      <ul class="space-y-1">
        <li class="flex gap-1.5"><code class="shrink-0 rounded bg-gray-100 px-1 py-0.5 text-[10px] text-gray-800">text</code><span>starts with</span></li>
        <li class="flex gap-1.5"><code class="shrink-0 rounded bg-gray-100 px-1 py-0.5 text-[10px] text-gray-800">*text</code><span>anywhere in the field</span></li>
        <li class="flex gap-1.5"><code class="shrink-0 rounded bg-gray-100 px-1 py-0.5 text-[10px] text-gray-800">&gt; &lt; &gt;= &lt;=</code><span>numeric/date comparison</span></li>
        <li class="flex gap-1.5"><code class="shrink-0 rounded bg-gray-100 px-1 py-0.5 text-[10px] text-gray-800">&gt;=A&lt;=B</code><span>range</span></li>
      </ul>
    </div>
  `,
})
export class FilterHelpTooltipComponent {}
